# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lhoodcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call('stm_lhoodcpp', PACKAGE = 'stm', eta, beta, doc_ct, mu, siginv)
}

gradcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call('stm_gradcpp', PACKAGE = 'stm', eta, beta, doc_ct, mu, siginv)
}

hpbcpp <- function(eta, beta, doc_ct, mu, siginv, sigmaentropy) {
    .Call('stm_hpbcpp', PACKAGE = 'stm', eta, beta, doc_ct, mu, siginv, sigmaentropy)
}

estep_loop <- function(documents, beta_index, lambda, mu, update_mu, beta, siginv, sigmaentropy, N, V, K, A) {
    .Call('stm_estep_loop', PACKAGE = 'stm', documents, beta_index, lambda, mu, update_mu, beta, siginv, sigmaentropy, N, V, K, A)
}

logistic_reg <- function(x, y) {
    .Call('stm_logistic_reg', PACKAGE = 'stm', x, y)
}

